version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: algotrading
      POSTGRES_USER: atharvapurohit
      POSTGRES_PASSWORD: 1234

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python load_stock.py &&
             python load_csv_daily.py &&
             python manage.py apply_sql_procs &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: